export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_RESET = "GET_PRODUCTS_RESET";
export const REFRESH_USAGE_PRODUCTS = "REFRESH_USAGE_PRODUCTS";
export const REFRESH_USAGE_PRODUCTS_RESET = "REFRESH_USAGE_PRODUCTS_RESET";

export const GET_COMPANIES_START = "GET_COMPANIES_START";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAIL = "GET_COMPANIES_FAIL";

export const REFRESH_BASKET = "REFRESH_BASKET";
export const REMOVE_BASKET = "REMOVE_BASKET";

